# Image used for PrairieLearn external grading of R questions
# as well as general support of STAT 430 Data Science Programming
# Methods (during 2019-2020) and STAT 447 (since 2021)

# Alton Barbehenn and Dirk Eddelbuettel, 2019-2022

# Before we based our image on prairielearn/centos7-python, 
# and that worked, but it was harder to maintian and a lot 
# than we needed. Now we're using rocker/tidyverse as our
# base because it's more focused and solves the prerequisites
# for us, along with providing many useful R packages. 

FROM eddelbuettel/r2u:22.04

# Needed to properly handle UTF-8
ENV PYTHONIOENCODING=UTF-8

# Install required packahes
RUN apt-get update && apt-get install -y \
        curl \
	git \
	sqlite3 \
        sudo \
        && echo "options(diffobj.brightness=\"dark\")" >> /etc/R/Rprofile.site

## Install R packages, which thanks to r2u, gets us binaries
RUN install.r \
        bench \
        data.table \
        devtools \
        diffobj \
        doParallel \
        dygraphs \
        flexdashboard \
        foreach \
        fs \
        future.apply \
        gh \
        git2r \
        igraph \
        lintr \
        memoise \
        microbenchmark \
        png \
        RcppArmadillo \
        rex \
        RSQLite \
        RUnit \
        shiny \
        testthat \
        tidyverse \
        tinytest \
        ttdo \
        unix \
        xts

# Install plr -- for now (?) from GH; also install visualTest
RUN installGithub.r stat447/plr MangoTheCat/visualTest

RUN useradd ag \ 
	&& mkdir /home/ag \
	&& chown ag:ag /home/ag \
	&& echo "[user]" > /home/ag/.gitconfig \
	&& echo "	name = Autograding User" >> /home/ag/.gitconfig \
	&& echo "	email = ag@nowhere" >> /home/ag/.gitconfig \
	&& chown ag:ag /home/ag/.gitconfig
